# This is a test change to trigger the workflow
name: CI Workflow


on:
  push:
    branches:
      - main  # or your default branch name


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm test
